import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Responsive Layout</title>
        <link rel="stylesheet" href="styles.css"></link>
      </head>
      <body className="wrapper">
        <div className="left">
          <div className="search-section">
            <input
              type="text"
              placeholder="Search or start new chat"
              className="search-input"
            />
            <button className="search-button">Search</button>
          </div>
          <div className="chats-section">
            {}
            <div className="blue-text chats">Chats</div>
          </div>
        </div>
        <div className="right">
          {children}
        </div>
      </body>
    </html>
  );
}
